sudo: required
dist: xenial

language: c

addons:
  apt:
    packages: [ liblua5.3-dev ]

matrix:
  include:
  - os: linux
    compiler: gcc
    env: TARGET=linux2628 FLAGS=
  - os: linux
    compiler: gcc
    env: TARGET=linux2628 FLAGS="USE_ZLIB=1 USE_PCRE=1 USE_LUA=1 USE_OPENSSL=1"
  - os: linux
    compiler: clang
    env: TARGET=linux2628 FLAGS=
  - os: osx
    compiler: clang
    env: TARGET=generic FLAGS=

install:
  - git clone https://github.com/VTest/VTest.git ../vtest
  # Special flags due to: https://github.com/vtest/VTest/issues/12
  - make -C ../vtest FLAGS="-O2 -s -Wall"

before_script:
  # This is a fix for the super long TMPDIR on Mac making
  # the unix socket path names exceed the maximum allowed
  # length.
  - sed -i'.original' '/TESTDIR=.*haregtests/s/haregtests-.*XXXXXX/regtest.XXX/' scripts/run-regtests.sh

script:
  - make CC=$CC V=1 TARGET=$TARGET $FLAGS
  - ./haproxy -vv
  - env VTEST_PROGRAM=../vtest/vtest make reg-tests

after_failure:
  - |
    for folder in ${TMPDIR:-/tmp}/*regtest*/vtc.*; do
      cat $folder/INFO
      cat $folder/LOG
    done
