sudo: required
dist: xenial

language: c

matrix:
  include:
#  - os: linux
#    compiler: gcc
#    env: TARGET=linux2628
  - os: linux
    compiler: clang
    env: TARGET=linux2628 USE_THREAD=1 USE_OPENSSL=1 USE_PCRE=1 USE_ZLIB=1 USE_GETADDRINFO=1
#  - os: osx
#    compiler: clang
#    env: TARGET=osx SSL_LIB=/usr/local/opt/openssl/lib SSL_INC=/usr/local/opt/openssl/include TMPDIR=/var/tmp

install:
  - git clone https://github.com/VTest/VTest.git ../vtest
  - make -C ../vtest

script:
  - make CC=$CC V=1 TARGET=$TARGET USE_THREAD=${USE_THREAD} USE_OPENSSL=${USE_OPENSSL} USE_PCRE=${USE_PCRE} USE_ZLIB=${USE_ZLIB} USE_GETADDRINFO=${USE_GETADDRINFO}
  - make reg-tests PATH=${PATH}:${PWD}/../vtest VTEST_PROGRAM="../vtest/vtest -v"
